ARG CMAKE_VERSION="3.23.4"
FROM ubuntu:18.04 AS vdr-builder
ARG CMAKE_VERSION

RUN apt-get update && \
  apt-get install -y \
  build-essential \
  git \
  curl

# Temp hack for QEMU-compatible rust
#RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.56.0
ENV SHELL "/bin/sh"
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sed 's#/proc/self/exe#$SHELL#g' | sh -s -- -y
RUN echo "[net]" >> ~/.cargo/config.toml && \
  echo "  git-fetch-with-cli=true" >> ~/.cargo/config.toml

ENV PATH=/root/.cargo/bin:$PATH
ENV RUST_BACKTRACE=1

RUN git clone https://github.com/mattrglobal/ffi-bbs-signatures.git && \
  cd ffi-bbs-signatures && \
  mkdir -p ./out && ./scripts/build.sh LINUX ./out

# VDR
RUN apt-get update && \
  apt-get install -y \
  cmake \
  libzmq5-dev \
  libssl-dev

RUN curl -sOL https://github.com/Kitware/CMake/archive/v${CMAKE_VERSION}.tar.gz && \
  tar -xvf v${CMAKE_VERSION}.tar.gz && \
  cd ./CMake-${CMAKE_VERSION} && \
  cmake . && \
  make && \
  make install

ENV BUILD_FEATURES zmq_vendored

# hack for replacing version to 0.3 since latest release did not build
RUN git clone https://github.com/hyperledger/indy-vdr.git && \
  sed -i "s/0.4.0/0.3.9/" /indy-vdr/libindy_vdr/Cargo.toml && \
  sed -i "s/0.4/0.3/" /indy-vdr/indy-vdr-proxy/Cargo.toml && \
  sed -i "s/0.4.0/0.3.9/" /indy-vdr/wrappers/python/indy_vdr/version.py && \
  cd ./indy-vdr && \
  cargo build --lib --release

ENV BUILD_FEATURES ""

# arm + amd compatible Dockerfile
FROM ghcr.io/findy-network/findy-base:indy-1.16.ubuntu-18.04 AS indy-base

FROM python:3.9-slim

# Copy both libs and wrapper code

# BBS
COPY --from=vdr-builder /ffi-bbs-signatures/out/linux/libbbs.so /usr/lib/libbbs.so
COPY --from=vdr-builder /ffi-bbs-signatures /ffi-bbs-signatures

# VDR
COPY --from=vdr-builder /indy-vdr/target/release/libindy_vdr.a /usr/lib/libindy_vdr.a
COPY --from=vdr-builder /indy-vdr/target/release/libindy_vdr.d /usr/lib/libindy_vdr.d
COPY --from=vdr-builder /indy-vdr/target/release/libindy_vdr.rlib /usr/lib/libindy_vdr.rlib
COPY --from=vdr-builder /indy-vdr/target/release/libindy_vdr.so /usr/lib/libindy_vdr.so
COPY --from=vdr-builder /indy-vdr /indy-vdr

RUN apt-get update \
  && apt-get install -y git gnupg2 software-properties-common curl build-essential

# install indy deps and files from base
RUN apt-get update && apt-get install -y libsodium23 libssl1.1 libzmq5
COPY --from=indy-base /usr/include/indy /usr/include/indy
COPY --from=indy-base /usr/lib/libindy.a /usr/lib/libindy.a
COPY --from=indy-base /usr/lib/libindy.so /usr/lib/libindy.so