ARG ASKAR_VERSION="0.2.7"
ARG CREDX_VERSION="0.3.1"
#ARG VDR_VERSION="0.3.4"

FROM ghcr.io/lauravuo/aries-agent-test-harness/acapy-main-base

RUN mkdir -p /aries-backchannels
WORKDIR /aries-backchannels

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq

# install local wrappers
RUN python3 -m pip install /aries-askar-${ASKAR_VERSION}/wrappers/python
RUN python3 -m pip install /ffi-bbs-signatures/wrappers/python
RUN python3 -m pip install /indy-shared-rs-${CREDX_VERSION}/wrappers/python
RUN python3 -m pip install /indy-vdr/wrappers/python

COPY python/requirements.txt python/
COPY acapy/requirements-main.txt acapy/
RUN pip install -r python/requirements.txt -r acapy/requirements-main.txt

# Copy the necessary files from the AATH Backchannel sub-folders
COPY python python
COPY acapy acapy
COPY data ./

# The Backchannel is looking for it in ./bin, copy a file that invokes the ACA-Py installed script in /usr/local/bin
RUN mkdir -p ./bin
COPY acapy/bin/aca-py ./bin/aca-py
RUN chmod +x ./bin/aca-py

ENV PYTHONPATH=/aries-backchannels
ENV RUNMODE=docker

RUN ./bin/aca-py --version > ./acapy-version.txt

ENV ACAPY_LOG_LEVEL debug

ENTRYPOINT ["bash", "acapy/ngrok-wait.sh"]
